version: '3.8'

services:
  backend:
    build: ../backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.main:app --host 0.0.0.0 --reload'
    volumes:
      - ../backend:/backend
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    expose:
       - 5432
    environment:
       - POSTGRES_USER=fastapi_traefik
       - POSTGRES_PASSWORD=fastapi_traefik
       - POSTGRES_DB=fastapi_traefik

volumes:
  postgres_data: